# https://www.baeldung.com/spring-profiles
# https://www.springcloud.io/post/2022-04/spring-samesite/#gsc.tab=0

server:
  servlet:
    session:
      cookie:
        same-site: none

# https://stackoverflow.com/questions/39401010/why-is-v2-api-docs-the-default-url-when-using-springfox-and-swagger2
#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /jishonotes/swaggerdocs/v2/api-docs

spring:
  inmemdb: true
  dangerous-mode: true
  use-swagger-ui: false
  jpa:
    show-sql: false
    generate-ddl: true